name: continuous-delivery-deployment
on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
jobs:
  build-and-deploy:   
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: 📦 Build project
      run: npm run build --if-present
      # Deploy to Netlify with a personalized message
      - name: 🚀 Deploy to Netlify
        id: deploy-netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy -m 'v${{ steps.package-version.outputs.current-version}} ・ ${{ github.head_ref }}'
