name: practice-continuous-test
on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - run: npm install
      - run: npm run test
